apiVersion: v1
kind: Service
metadata:
  name: {{ template "gogs.fullname" . }}
  labels:
    app: {{ template "gogs.name" . }}
    chart: {{ template "gogs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.svcType }}
  ports:
  - name: web
    nodePort: 0
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: ssh
    nodePort: 0
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: {{ template "gogs.name" . }}
    release: {{ .Release.Name }}
